import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "360 Motion Studio",
  description: "Generated by create next appUnlock the power of captivating branding, dynamic 3D product designs, compelling commercial videos, and seamless website development with 360MotionStudio. Elevate your brand's presence online with our expert services. Discover how our innovative solutions can transform your digital footprint today!",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <Header />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
